/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    solutions: Solution;
    resources: Resource;
    'resource-sections': ResourceSection;
    faqs: Faq;
    'team-members': TeamMember;
    'partner-logos': PartnerLogo;
    'product-features': ProductFeature;
    'how-it-works-steps': HowItWorksStep;
    media: Media;
    companies: Company;
    subscriptions: Subscription;
    invoices: Invoice;
    leads: Lead;
    'support-tickets': SupportTicket;
    users: User;
    analytics: Analytics;
    'email-campaigns': EmailCampaign;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'resource-sections': ResourceSectionsSelect<false> | ResourceSectionsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'partner-logos': PartnerLogosSelect<false> | PartnerLogosSelect<true>;
    'product-features': ProductFeaturesSelect<false> | ProductFeaturesSelect<true>;
    'how-it-works-steps': HowItWorksStepsSelect<false> | HowItWorksStepsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'support-tickets': SupportTicketsSelect<false> | SupportTicketsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'about-content': AboutContent;
    'pricing-config': PricingConfig;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-content': AboutContentSelect<false> | AboutContentSelect<true>;
    'pricing-config': PricingConfigSelect<false> | PricingConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage all content for service pages — text, features, media, and pricing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL slug (e.g., "cognitive-surveillance"). Must be URL-safe, lowercase, hyphenated.
   */
  slug: string;
  title: string;
  category?: ('forensic' | 'surveillance' | 'automation' | 'iot' | 'consulting') | null;
  /**
   * Uncheck to hide this service without deleting it.
   */
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first on the services list page.
   */
  orderIndex?: number | null;
  /**
   * Accent color for the service card and icon on the list page.
   */
  colorTheme?: ('cyan' | 'violet' | 'emerald' | 'amber' | 'rose' | 'indigo') | null;
  /**
   * Short tagline shown on the service card and detail page hero.
   */
  subtitle?: string | null;
  /**
   * Full description shown in the "Overview" section of the service detail page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hero stats strip (4 recommended). Example: value "< 3s", label "Search 1TB Footage".
   */
  stats?:
    | {
        /**
         * Bold metric (e.g., "< 3s" or "99.2%").
         */
        value: string;
        /**
         * Descriptor below the value.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Three-step process shown below the hero. Recommended: exactly 3 steps.
   */
  howItWorks?:
    | {
        title: string;
        description: string;
        /**
         * Icon displayed on this step.
         */
        iconName?:
          | (
              | 'search'
              | 'database'
              | 'eye'
              | 'camera'
              | 'cpu'
              | 'brain'
              | 'bot'
              | 'network'
              | 'zap'
              | 'shield-alert'
              | 'bell'
              | 'file-check'
              | 'clipboard-list'
              | 'settings'
              | 'plug'
              | 'trending-up'
              | 'book-open'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature cards shown in the "Key Capabilities" grid on the detail page (3 recommended).
   */
  features?:
    | {
        title: string;
        /**
         * One or two sentences explaining this feature.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Banner image displayed at the top of the service detail page. Recommended: 1920×1080px.
   */
  heroImage?: (number | null) | Media;
  /**
   * Additional images for the service gallery.
   */
  galleryImages?:
    | {
        image: number | Media;
        /**
         * Optional caption.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional video URL. Leave empty to hide the video player.
   */
  heroVideoUrl?: string | null;
  /**
   * Define Plus, Pro, and Enterprise pricing for this service.
   */
  plans?:
    | {
        name: 'Plus' | 'Pro' | 'Enterprise';
        /**
         * Base monthly price. Set to 0 for Enterprise to show "Custom" pricing.
         */
        monthlyPrice?: number | null;
        /**
         * Total price for a 12-month subscription. Savings vs monthly are auto-calculated and shown.
         */
        annualPrice?: number | null;
        /**
         * Short descriptor under the plan name (e.g., "Essential capabilities for smaller operations").
         */
        description?: string | null;
        /**
         * Optional badge text shown on card (e.g., "Most Popular", "Best Value"). Only one plan should have a badge.
         */
        badge?: string | null;
        /**
         * Highlights this plan card with accent border and elevated style. Only set for ONE plan per service.
         */
        isPopular?: boolean | null;
        /**
         * Optional custom discount label shown on this plan (e.g., "30% off this month"). Shows on top of auto-calculated savings.
         */
        discountNote?: string | null;
        planFeatures?:
          | {
              feature: string;
              /**
               * Uncheck to show this feature as crossed-out (not included).
               */
              included?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Button text. Default: "Get Started" for paid plans, "Contact Sales" for Enterprise.
         */
        ctaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO. Auto-filled from filename if left blank.
   */
  alt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage all content for solution pages — text, stats, feature sections, FAQs, and media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  /**
   * URL slug (e.g., "education"). Must be URL-safe, lowercase, hyphenated.
   */
  slug: string;
  /**
   * Display name shown on cards and the detail page hero.
   */
  title: string;
  category?: ('industry' | 'use-case') | null;
  /**
   * Uncheck to hide this solution without deleting it.
   */
  isPublished?: boolean | null;
  /**
   * Short headline shown on cards and the detail page hero (e.g., "Protect Students with Real-Time AI").
   */
  subtitle?: string | null;
  /**
   * Brief summary shown on the solutions list page card (2-3 sentences).
   */
  shortDescription?: string | null;
  /**
   * Full description shown in the "Overview" section of the detail page.
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Benefit cards shown in the "Key Capabilities" grid (3 recommended).
   */
  keyBenefits?:
    | {
        title: string;
        /**
         * One or two sentences explaining this benefit.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Key metrics shown in the stats grid (4 recommended). Example: value "73%", label "Faster Response".
   */
  stats?:
    | {
        /**
         * The bold number/text (e.g., "73%" or "< 2s").
         */
        value: string;
        /**
         * The description below the value (e.g., "Faster Emergency Response").
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Alternating two-column sections: title + description on one side, bullet points on the other.
   */
  featureSections?:
    | {
        title: string;
        /**
         * Introductory paragraph for this feature section.
         */
        description?: string | null;
        /**
         * Checkmark bullet points listing specific capabilities.
         */
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Accordion FAQ section at the bottom of the detail page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Banner image displayed at the top of the solution detail page. Recommended: 1920×1080px.
   */
  heroImage?: (number | null) | Media;
  /**
   * Additional images for the solution gallery.
   */
  galleryImages?:
    | {
        image: number | Media;
        /**
         * Optional caption.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional video URL. Leave empty to hide the video player.
   */
  heroVideoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload documents, PDFs, videos, and stories. PDFs are automatically scanned and their text extracted into the content field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-fill from title if left blank.
   */
  slug: string;
  category:
    | 'Blog'
    | 'Documentation'
    | 'Case Study'
    | 'White Paper'
    | 'Library'
    | 'Customer Story'
    | 'Partner'
    | 'Grant'
    | 'AI Agent';
  /**
   * Short summary shown on cards and meta descriptions.
   */
  summary?: string | null;
  /**
   * Full article content. Auto-populated when a PDF is uploaded.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hero image shown at the top of the resource page and on cards.
   */
  coverImage?: (number | null) | Media;
  /**
   * YouTube or Vimeo URL — embedded inline on the detail page (e.g. https://www.youtube.com/watch?v=xxx).
   */
  videoUrl?: string | null;
  /**
   * Upload a PDF — text is automatically extracted into the content field. A download button appears on the page.
   */
  pdfFile?: (number | null) | Media;
  /**
   * Upload a Word/DOCX document — a download button appears on the detail page.
   */
  docxFile?: (number | null) | Media;
  /**
   * Optional external URL — opens in new tab instead of the detail page.
   */
  externalLink?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which section this resource belongs to on the Resources page. Leave blank to show in "All Resources".
   */
  section?: (number | null) | ResourceSection;
  /**
   * Show this resource in the Resources navigation dropdown menu.
   */
  featuredInNav?: boolean | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Named groups for organizing documents and files on the Resources page. Create sections like "Our Journey", "White Papers", or "Blog".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-sections".
 */
export interface ResourceSection {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g. "our-journey"). Fill from title.
   */
  slug: string;
  /**
   * Optional short description shown below the section title on the Resources page.
   */
  description?: string | null;
  /**
   * Lower numbers appear first. Sections are sorted by this field.
   */
  orderIndex?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * e.g. General, Technical, Product, Billing
   */
  category?: string | null;
  sortOrder?: number | null;
  /**
   * Optional file attachment
   */
  attachment?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Job title/role (e.g., "Co-Founder & CEO")
   */
  role: string;
  /**
   * Short personal motto shown as a chat-style quote under their name (e.g., "Security is not a product, it's a process.")
   */
  motto?: string | null;
  bio?: string | null;
  image?: (number | null) | Media;
  socialLinkedin?: string | null;
  socialTwitter?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage partner and trusted-by logos shown in the homepage infinite scroll.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-logos".
 */
export interface PartnerLogo {
  id: number;
  /**
   * Company / partner name (used as alt text and title)
   */
  name: string;
  /**
   * Upload the partner logo image. IMPORTANT: Ensure the image has a TRANSPARENT background (PNG or SVG) so it sits cleanly inside the white box containers.
   */
  logo: number | Media;
  /**
   * Alternative: paste an external logo URL if you are not uploading a file
   */
  logoUrl?: string | null;
  /**
   * Optional: partner website URL (makes the logo clickable)
   */
  websiteUrl?: string | null;
  /**
   * Lower numbers appear first in the scroll
   */
  displayOrder?: number | null;
  /**
   * Uncheck to hide this logo from the website without deleting it
   */
  isActive?: boolean | null;
  /**
   * Optional: link to a company record in the CMS
   */
  company?: (number | null) | Company;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  industry?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  status?: ('active' | 'suspended' | 'deleted') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-features".
 */
export interface ProductFeature {
  id: number;
  title: string;
  description: string;
  /**
   * Image or video URL
   */
  mediaUrl?: string | null;
  mediaType?: ('image' | 'video') | null;
  featuresList?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  imagePosition?: ('left' | 'right') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-steps".
 */
export interface HowItWorksStep {
  id: number;
  title: string;
  description?: string | null;
  /**
   * e.g. "01", "02"
   */
  stepNumber: string;
  /**
   * Lucide icon name (e.g., "AlertCircle", "Zap")
   */
  iconName?: string | null;
  media?: (number | null) | Media;
  mediaType?: ('image' | 'video') | null;
  mediaFit?: ('cover' | 'contain' | 'fill') | null;
  /**
   * Tailwind gradient classes (e.g., "from-red-500 to-orange-500")
   */
  colorTheme?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  company: number | Company;
  service: number | Service;
  status: 'ACTIVE' | 'CANCELLED' | 'TRIAL';
  startDate: string;
  endDate?: string | null;
  nextBillingDate?: string | null;
  usersAllowed?: number | null;
  /**
   * Custom price override (decimal)
   */
  customPrice?: number | null;
  /**
   * Stripe subscription ID
   */
  stripeSubscriptionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  subscription: number | Subscription;
  billingPeriodStart: string;
  billingPeriodEnd: string;
  amount: number;
  vat?: number | null;
  currency?: string | null;
  status: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE';
  pdfUrl?: string | null;
  issuedAt?: string | null;
  paidAt?: string | null;
  stripeInvoiceId?: string | null;
  /**
   * Line items for this invoice
   */
  items?:
    | {
        description: string;
        quantity: number;
        unitPrice: number;
        total: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  message?: string | null;
  /**
   * Where the lead came from (e.g., "contact-form", "demo-request")
   */
  source?: string | null;
  status?: ('NEW' | 'CONTACTED' | 'QUALIFIED' | 'CONVERTED' | 'LOST') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
  id: number;
  title: string;
  description?: string | null;
  company: number | Company;
  submittedBy: number | User;
  assignedTo?: (number | null) | User;
  status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED';
  messages?:
    | {
        user: number | User;
        message: string;
        sentAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'SUPER_ADMIN' | 'COMPANY_ADMIN' | 'STAFF';
  /**
   * The company this user belongs to
   */
  company?: (number | null) | Company;
  avatar?: (number | null) | Media;
  phone?: string | null;
  address?: string | null;
  resetCode?: string | null;
  resetCodeExpiration?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  company?: (number | null) | Company;
  date: string;
  pageViews?: number | null;
  uniqueVisitors?: number | null;
  serviceUsage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  subject: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Filter criteria for recipients (e.g., {"role": "COMPANY_ADMIN"})
   */
  recipientFilter?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Count of emails sent
   */
  sentTo?: number | null;
  opened?: number | null;
  clicked?: number | null;
  status?: ('draft' | 'scheduled' | 'sent' | 'failed') | null;
  scheduledAt?: string | null;
  sentAt?: string | null;
  /**
   * Individual recipient tracking
   */
  recipients?:
    | {
        user?: (number | null) | User;
        sentAt?: string | null;
        openedAt?: string | null;
        clickedAt?: string | null;
        bounced?: boolean | null;
        errorMessage?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: string;
  entityType: string;
  entityId?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'resource-sections';
        value: number | ResourceSection;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partner-logos';
        value: number | PartnerLogo;
      } | null)
    | ({
        relationTo: 'product-features';
        value: number | ProductFeature;
      } | null)
    | ({
        relationTo: 'how-it-works-steps';
        value: number | HowItWorksStep;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'support-tickets';
        value: number | SupportTicket;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'analytics';
        value: number | Analytics;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  isPublished?: T;
  orderIndex?: T;
  colorTheme?: T;
  subtitle?: T;
  description?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        title?: T;
        description?: T;
        iconName?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  heroImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  heroVideoUrl?: T;
  plans?:
    | T
    | {
        name?: T;
        monthlyPrice?: T;
        annualPrice?: T;
        description?: T;
        badge?: T;
        isPopular?: T;
        discountNote?: T;
        planFeatures?:
          | T
          | {
              feature?: T;
              included?: T;
              id?: T;
            };
        ctaLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  isPublished?: T;
  subtitle?: T;
  shortDescription?: T;
  longDescription?: T;
  keyBenefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featureSections?:
    | T
    | {
        title?: T;
        description?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heroImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  heroVideoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  videoUrl?: T;
  pdfFile?: T;
  docxFile?: T;
  externalLink?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  section?: T;
  featuredInNav?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-sections_select".
 */
export interface ResourceSectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  orderIndex?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  attachment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  motto?: T;
  bio?: T;
  image?: T;
  socialLinkedin?: T;
  socialTwitter?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-logos_select".
 */
export interface PartnerLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  websiteUrl?: T;
  displayOrder?: T;
  isActive?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-features_select".
 */
export interface ProductFeaturesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mediaUrl?: T;
  mediaType?: T;
  featuresList?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  displayOrder?: T;
  isActive?: T;
  imagePosition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-steps_select".
 */
export interface HowItWorksStepsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stepNumber?: T;
  iconName?: T;
  media?: T;
  mediaType?: T;
  mediaFit?: T;
  colorTheme?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  industry?: T;
  address?: T;
  email?: T;
  phone?: T;
  website?: T;
  logo?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  company?: T;
  service?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  nextBillingDate?: T;
  usersAllowed?: T;
  customPrice?: T;
  stripeSubscriptionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  subscription?: T;
  billingPeriodStart?: T;
  billingPeriodEnd?: T;
  amount?: T;
  vat?: T;
  currency?: T;
  status?: T;
  pdfUrl?: T;
  issuedAt?: T;
  paidAt?: T;
  stripeInvoiceId?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        total?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets_select".
 */
export interface SupportTicketsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  company?: T;
  submittedBy?: T;
  assignedTo?: T;
  status?: T;
  messages?:
    | T
    | {
        user?: T;
        message?: T;
        sentAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  avatar?: T;
  phone?: T;
  address?: T;
  resetCode?: T;
  resetCodeExpiration?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  company?: T;
  date?: T;
  pageViews?: T;
  uniqueVisitors?: T;
  serviceUsage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  subject?: T;
  body?: T;
  recipientFilter?: T;
  sentTo?: T;
  opened?: T;
  clicked?: T;
  status?: T;
  scheduledAt?: T;
  sentAt?: T;
  recipients?:
    | T
    | {
        user?: T;
        sentAt?: T;
        openedAt?: T;
        clickedAt?: T;
        bounced?: T;
        errorMessage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Central control panel for all site-wide settings, branding, hero images, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Upload the main website logo (SVG or transparent PNG, recommended 200×60px).
   */
  siteLogo?: (number | null) | Media;
  /**
   * Displayed in the browser tab and footer.
   */
  siteName?: string | null;
  /**
   * Shown below the logo in the footer.
   */
  siteTagline?: string | null;
  /**
   * 🌤️ DAY MODE hero background image. Upload a wide landscape image (recommended: 2560×1440px minimum). The image will scale responsively — it will NOT crop or break on any screen size.
   */
  heroImageDay?: (number | null) | Media;
  /**
   * 🌙 NIGHT MODE hero background image. Upload a wide landscape image (recommended: 2560×1440px minimum). Same dimensions as the day image for seamless theme switching.
   */
  heroImageNight?: (number | null) | Media;
  /**
   * Main headline text displayed over the hero image.
   */
  heroHeadline?: string | null;
  /**
   * The portion of the headline that gets the gradient color effect.
   */
  heroHighlightText?: string | null;
  /**
   * Subtitle paragraph shown below the headline.
   */
  heroSubtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Font Size (px)
   */
  heroSubtitleSize?: number | null;
  /**
   * Text for the primary call-to-action button.
   */
  heroCTAText?: string | null;
  /**
   * URL the primary CTA button links to.
   */
  heroCTALink?: string | null;
  /**
   * Text for the secondary button (YouTube link).
   */
  heroSecondaryCTAText?: string | null;
  /**
   * URL for the secondary button (e.g., YouTube link).
   */
  heroSecondaryCTALink?: string | null;
  /**
   * Add hero images for each page (services, solutions, pricing, etc.). Each page can have separate day and night images.
   */
  pageHeroes?:
    | {
        /**
         * Which page this hero image is for.
         */
        pageSlug: 'services' | 'solutions' | 'pricing' | 'about' | 'contact' | 'resources';
        /**
         * 🌤️ Day mode hero image for this page (2560×1440px recommended).
         */
        dayImage?: (number | null) | Media;
        /**
         * 🌙 Night mode hero image for this page (2560×1440px recommended).
         */
        nightImage?: (number | null) | Media;
        /**
         * Page-specific headline. Leave blank to use the page default.
         */
        headline?: string | null;
        /**
         * Page-specific subtitle text.
         */
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  contactInfo?: {
    /**
     * The public contact email address.
     */
    email?: string | null;
    /**
     * Primary contact phone number.
     */
    phone?: string | null;
    /**
     * Secondary contact phone number (optional).
     */
    phone2?: string | null;
    /**
     * Physical office address.
     */
    address?: string | null;
    /**
     * Google Maps iframe embed code or src URL. This will render the interactive grayscale map in the footer.
     */
    map_embed?: string | null;
  };
  partnerLogosSection?: {
    enabled?: boolean | null;
    /**
     * Text shown above the scrolling logos.
     */
    headline?: string | null;
  };
  whyKingsforthSection?: {
    title?: string | null;
    subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Size (px)
     */
    subtitleSize?: number | null;
  };
  productShowcaseSection?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Size (px)
     */
    descriptionSize?: number | null;
    /**
     * Upload a 16:9 image or short looping video of the dashboard.
     */
    showcaseMedia?: (number | null) | Media;
  };
  statsSection?: {
    stats?:
      | {
          /**
           * e.g. 1M+
           */
          value: string;
          /**
           * e.g. Incidents Prevented
           */
          label: string;
          /**
           * Lucide React icon name (e.g. Activity, Shield, Users)
           */
          iconName?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  howItWorksSection?: {
    title?: string | null;
    subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Size (px)
     */
    subtitleSize?: number | null;
    /**
     * The timeline steps displaying down the page.
     */
    steps?:
      | {
          /**
           * e.g. "01", "02"
           */
          stepNumber: string;
          title: string;
          description?: string | null;
          /**
           * Lucide icon name (e.g. "AlertCircle", "Zap")
           */
          iconName?: string | null;
          /**
           * Tailwind gradient (e.g. "from-cyan-500 to-blue-500")
           */
          colorTheme?: string | null;
          /**
           * Upload the image/gif/video to show beside this step.
           */
          media?: (number | null) | Media;
          mediaType?: ('image' | 'video') | null;
          mediaFit?: ('cover' | 'contain') | null;
          id?: string | null;
        }[]
      | null;
  };
  coreCapabilitiesSection?: {
    title?: string | null;
    subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Size (px)
     */
    subtitleSize?: number | null;
  };
  finalCtaSection?: {
    title?: string | null;
    subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Size (px)
     */
    subtitleSize?: number | null;
    primaryButtonText?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
  };
  resourcesPageHero?: {
    /**
     * Main heading on the Resources page.
     */
    heading?: string | null;
    /**
     * Subheading paragraph shown below the main heading.
     */
    subheading?: string | null;
  };
  /**
   * Heading shown above the LLM platform links on the Resources page.
   */
  llmSectionHeading?: string | null;
  /**
   * Add AI platforms (ChatGPT, Claude, Gemini, etc.) for visitors to start a conversation about Kingsforth. Each link opens in a new tab.
   */
  llmLinks?:
    | {
        /**
         * Display name, e.g. ChatGPT, Claude, Gemini
         */
        name: string;
        /**
         * Short description shown under the name, e.g. "Start a conversation about Kingsforth with ChatGPT."
         */
        description?: string | null;
        /**
         * Full URL including pre-filled query, e.g. https://chatgpt.com/?q=Tell+me+about+Kingsforth+AI
         */
        url: string;
        /**
         * Hex color for the icon circle background/accent, e.g. #10a37f for ChatGPT green.
         */
        iconColor?: string | null;
        /**
         * Single letter/emoji to show inside the icon circle, e.g. G for ChatGPT, C for Claude.
         */
        iconLetter?: string | null;
        /**
         * Uncheck to hide this link from the public Resources page.
         */
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default sender name for system emails.
   */
  emailFromName?: string | null;
  /**
   * Default sender email address.
   */
  emailFromAddress?: string | null;
  teamSectionHeading?: string | null;
  aboutSectionHeading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 */
export interface AboutContent {
  id: number;
  mission?: {
    title?: string | null;
    content?: string | null;
    image?: (number | null) | Media;
  };
  vision?: {
    title?: string | null;
    content?: string | null;
    image?: (number | null) | Media;
  };
  story?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  stats?:
    | {
        label: string;
        value: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Platform pricing tiers, billing discounts, and service add-on prices for the Pricing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config".
 */
export interface PricingConfig {
  id: number;
  /**
   * Pricing page headline
   */
  headline?: string | null;
  /**
   * Pricing page subheadline
   */
  subheadline?: string | null;
  /**
   * Platform tiers (e.g. Starter — 5 cameras, Professional — 50 cameras, Enterprise)
   */
  tiers?:
    | {
        /**
         * Plan name, e.g. "Starter"
         */
        name: string;
        /**
         * Short descriptor, e.g. "Up to 5 cameras"
         */
        tagline?: string | null;
        /**
         * One-line plan description
         */
        description?: string | null;
        /**
         * Base monthly price in BDT (৳). Set to 0 for custom/enterprise pricing.
         */
        monthlyPrice?: number | null;
        /**
         * If checked, shows "Contact Sales" instead of a price
         */
        isCustomPrice?: boolean | null;
        /**
         * Percentage discount for annual billing (e.g. 20 = 20% off monthly price)
         */
        annualDiscount?: number | null;
        /**
         * Highlights this plan as recommended
         */
        isPopular?: boolean | null;
        /**
         * Badge label, e.g. "Most Popular"
         */
        badge?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        /**
         * Feature list shown on the plan card
         */
        features?:
          | {
              label: string;
              /**
               * Checked = included (green tick). Unchecked = not included (grey X).
               */
              included?: boolean | null;
              /**
               * Optional qualifier, e.g. "up to 5 simultaneous"
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AI module add-ons available to bundle with any base plan.
   */
  serviceAddOns?:
    | {
        /**
         * Exact slug from Services collection, e.g. "cognitive-surveillance"
         */
        serviceSlug: string;
        /**
         * Display name for the add-on card
         */
        serviceTitle: string;
        /**
         * Monthly add-on price in BDT (৳)
         */
        monthlyAddOnPrice: number;
        /**
         * Annual add-on price in BDT (৳) per month when billed annually. Leave blank to auto-apply 20% off monthly price.
         */
        annualAddOnPrice?: number | null;
        /**
         * One-line description shown on the add-on card
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print shown below pricing, e.g. VAT information or cancellation policy.
   */
  billingNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteLogo?: T;
  siteName?: T;
  siteTagline?: T;
  heroImageDay?: T;
  heroImageNight?: T;
  heroHeadline?: T;
  heroHighlightText?: T;
  heroSubtitle?: T;
  heroSubtitleSize?: T;
  heroCTAText?: T;
  heroCTALink?: T;
  heroSecondaryCTAText?: T;
  heroSecondaryCTALink?: T;
  pageHeroes?:
    | T
    | {
        pageSlug?: T;
        dayImage?: T;
        nightImage?: T;
        headline?: T;
        subtitle?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        phone2?: T;
        address?: T;
        map_embed?: T;
      };
  partnerLogosSection?:
    | T
    | {
        enabled?: T;
        headline?: T;
      };
  whyKingsforthSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        subtitleSize?: T;
      };
  productShowcaseSection?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        descriptionSize?: T;
        showcaseMedia?: T;
      };
  statsSection?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              iconName?: T;
              id?: T;
            };
      };
  howItWorksSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        subtitleSize?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              title?: T;
              description?: T;
              iconName?: T;
              colorTheme?: T;
              media?: T;
              mediaType?: T;
              mediaFit?: T;
              id?: T;
            };
      };
  coreCapabilitiesSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        subtitleSize?: T;
      };
  finalCtaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        subtitleSize?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  resourcesPageHero?:
    | T
    | {
        heading?: T;
        subheading?: T;
      };
  llmSectionHeading?: T;
  llmLinks?:
    | T
    | {
        name?: T;
        description?: T;
        url?: T;
        iconColor?: T;
        iconLetter?: T;
        enabled?: T;
        id?: T;
      };
  emailFromName?: T;
  emailFromAddress?: T;
  teamSectionHeading?: T;
  aboutSectionHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  mission?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  story?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config_select".
 */
export interface PricingConfigSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  tiers?:
    | T
    | {
        name?: T;
        tagline?: T;
        description?: T;
        monthlyPrice?: T;
        isCustomPrice?: T;
        annualDiscount?: T;
        isPopular?: T;
        badge?: T;
        ctaLabel?: T;
        ctaLink?: T;
        features?:
          | T
          | {
              label?: T;
              included?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  serviceAddOns?:
    | T
    | {
        serviceSlug?: T;
        serviceTitle?: T;
        monthlyAddOnPrice?: T;
        annualAddOnPrice?: T;
        description?: T;
        id?: T;
      };
  billingNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}